server:
  port: 8087

mybatis:
  type-aliases-package: com.orange.servicechannel.entity
  mapper-locations: classpath:mapper/*.xml

#本机数据库配置
spring:
  datasource:
    name: orange
    url: jdbc:mysql://localhost:3306/orange?serverTimezone=Asia/Shanghai&useSSL=false
    username: orange
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #不指定type默认使用HikariCP连接池


